# Generated by Django 5.0.7 on 2024-09-24 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steganography', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 9, 24, 17, 6, 9, 815655, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
