# Generated by Django 5.1.1 on 2024-10-08 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steganography', '0002_message_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
